# Generated by Django 4.1 on 2022-09-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Us1111er',
        ),
    ]
